[tool.bandit]
exclude_dirs = ["api_app/tests_ma", "airlock_processor/tests", "airlock_processor/.venv", "resource_processor/tests_rp", "e2e_tests", "docs"]

[tool.pytest.ini_options]
asyncio_mode = "strict"
asyncio_default_fixture_loop_scope = "function"
